### ISSUE TITLE
Histogram on Targeted_phylum 

### ISSUE THREAD

**Issue by Yan-yang35** [PBrockmann/PANGEAE_Scraping#10]
Dear Patrick，

There 102 datasets for Ochrophyta, but the number shown in following figure is less than 100. Could you please check what cause this issue? 
![Targeted_phylum](https://github.com/PBrockmann/PANGAEA_Scraping/assets/67366500/ef20112a-f6c3-4df5-9755-257e7bfdf76a)

Best,
Yan

**Comment by PBrockmann** [comment]
The figure have been produced from a old snapshot of the repository.
I have 102 with the new figure... Just wait that I finish the work...

![Targeted_phylum](https://github.com/PBrockmann/PANGAEA_Scraping/assets/5402758/4b1d9c56-cffe-4fc3-b371-a91d23d04341)

**Comment by Yan-yang35** [comment]
Well noted with many thanks!
