### ISSUE TITLE
In the histogrammes, sort keywords by total numbers

### ISSUE THREAD

**Issue by Yan-yang35** [PBrockmann/PANGEAE_Scraping#2]
Hi Patrick，

Could we sort the keywords by total numbers rather than alphabetical order？Like the examples shown in 
[Examples.pptx](https://github.com/PBrockmann/PANGEAE_Scraping/files/7480810/Examples.pptx)
If it could be done, there will be no need to rename:
                            'North Atlantic': 'Atlantic North',
                            'South Atlantic': 'Atlantic South',
                            'North Pacific': 'Pacific North',
                            'South Pacific': 'Pacific South',

Many thanks and best regards,
Yan

**Comment by PBrockmann** [comment]
Done by a 
```dhisto.sort_values(by='Total', inplace=True, ascending=False)```
