### ISSUE TITLE
Format of histograms

### ISSUE THREAD

**Issue by Yan-yang35** [PBrockmann/PANGEAE_Scraping#3]
Dear Patrick，

Per discussed with Fred, we suggest making following changes to the histograms:

1.	Add legend;
2.	Remove the black edge lines of bars;
3.	Fill the orange bars with slash line, in case the paper will be print in black and white;
4.	Set the same width and height of these histograms.

Many thanks and best regards,
Yan

**Comment by PBrockmann** [comment]
Done. 
Updated the google doc as well.
Please insert them with respect to the width images (for example width in pixel x 2 / 1000).
