### ISSUE TITLE
Figure of cumulative number of papers

### ISSUE THREAD

**Issue by Yan-yang35** [PBrockmann/PANGEAE_Scraping#7]
Hi Patrick,
It would be appricated if you could also make following figure by Python. I have made this one by Sigmaplot, but I think it would be nice to make it coherent with the other figures you made in the paper. 
The data are from the "exported files". 
”Archived“ are papers included, "Not obtained" are papers not included due to "No answer from authors", "Incomplete" are papers not included due to "< 2 carbonate chemistry parameters", "Data lost" are papers not included due to "Data lost".
Y axis is the cumulative number of papers. For example, if 1 paper in year 1965, 1 paper in year 1966, the cumulative number in year 1966 is 1+1=2.
Year     Num of papers    Cumulative number of papers
1965             1                               1
1966             1                               2
1967             1                               3
![image](https://user-images.githubusercontent.com/67366500/145369028-2bf40109-13cb-476c-90cf-33867ab79883.png)

**Comment by PBrockmann** [comment]
Here is a first version.
Why is there 2022 year ?

![image](https://user-images.githubusercontent.com/5402758/145420789-f4af49a7-0b93-422e-83ff-0660179c577c.png)

https://github.com/PBrockmann/PANGEAE_Scraping/blob/main/PANGEAE_cumulativePapers_01.ipynb

**Comment by Yan-yang35** [comment]
Looks nice, thanks! The x-axis corresponds to the publication year. The publication year of following paper is 2022.
Wu, C., Kan, J., Narale, D. D., Liu, K., & Sun, J., 2022. Dynamics of bacterial communities during a seasonal hypoxia at the Bohai Sea: coupling and response between abundant and rare populations. Journal of Environmental Sciences 111:324-339.
I found the Year of two papers are "in press", could you please group them to 2022?
Could you please set x-axis start at 1965 and end at 2025, with increments of 5？
Thank you！

**Comment by PBrockmann** [comment]
I am really your assistant... Initially I wanted to give you the way to do those changes by yourself.

![image](https://user-images.githubusercontent.com/5402758/145573406-99dfff4e-69c4-4381-82c6-c3622e8fe93b.png)

The notebook is updated.

**Comment by Yan-yang35** [comment]
Thank you very much as always! Could you also please update this figure based on the file attached? 
[OAICC_20211210.csv](https://github.com/PBrockmann/PANGEAE_Scraping/files/7700673/OAICC_20211210.csv)

**Comment by PBrockmann** [comment]
Done

![image](https://user-images.githubusercontent.com/5402758/145806751-073458d9-c622-43a9-b6e2-84d5bdca8e5b.png)

**Comment by PBrockmann** [comment]
Done
