### ISSUE TITLE
Launch error

### ISSUE THREAD

**Issue by Yan-yang35** [PBrockmann/PANGEAE_Scraping#8]
Hi Patrick，

Fred and I are going to update the figures. I have tried to Launch binder, but I met some error. Could you kindly please check how to fix these error? Many thanks in advance!

Best regards,
Yan
![1687842145536](https://github.com/PBrockmann/PANGEAE_Scraping/assets/67366500/8c4aab48-eba9-466a-8bfc-715a7bd80451)

**Comment by PBrockmann** [comment]
I have updated the way the repository can be launched.
Also updated the notebooks with last OAICC_20230419.csv.

Note that I have corrected from a bad country the file named:  OAICCdb_20230419.utf8
Changed "EU--Germany" to "EU-Germany"

**Comment by PBrockmann** [comment]
I have just tested.  I have made some changes due to modules updates (pandas, ...).
It seems ok to reproduce all the figures with new files (https://oa-icc.ipsl.fr/checking/OAICC_20230419.csv).

**Comment by Yan-yang35** [comment]
Many thanks for your quick response! I have tried to run the notebooks and found out some issues of "PANGAEA_Country_affiliation_01" and "PANGAEA_cumulativePapers_01". Could you please check them again? Thanks.
![d92d3db57744db9e0b07dc29850cbf1](https://github.com/PBrockmann/PANGAEA_Scraping/assets/67366500/347b999b-25b4-4dd7-a2f5-b1c7fdd45aa2)
![d169ce1d1d2d4257a61493831edcb85](https://github.com/PBrockmann/PANGAEA_Scraping/assets/67366500/43d44c08-17c6-47b5-a340-1a8fd7920dc3)

**Comment by PBrockmann** [comment]
Hi,
Not really an error. Just a cell that has been affected by mistake to makdown rather to code.
When you have this kind of error, it is quite easy to fix.

It is done.
![image](https://github.com/PBrockmann/PANGAEA_Scraping/assets/5402758/f8de6932-26bd-42b8-8b44-bcb99b9daab3)

![image](https://github.com/PBrockmann/PANGAEA_Scraping/assets/5402758/4bfbc304-53af-4e62-98b9-ba7554ad8178)

Both notebooks run correclty from the cloud (binder).

Hope that it will be alright for you as well.

PS: When you describe an issue, it is easier to capture the text rather that capture images.

**Comment by Yan-yang35** [comment]
Many thanks again!
