### ISSUE TITLE
Citation Date is None

### ISSUE THREAD

**Issue by Yan-yang35** [PBrockmann/PANGEAE_Scraping#9]
Hi,
I found in notebook "PANGAEA_OAICC_histo_01", for some datasets, the citation dates are none. For example, "
PANGAEA.942326" and "PANGAEA.934173". Also on the Portal at page "Selection", Year is "Null" for these datasets.

Best regards,
Yan

**Comment by PBrockmann** [comment]
yes indeed. 

For exemple:
http://ws.pangaea.de/es/dataportal-oa-icc/pansimple/_search?q=_id:PANGAEA.960176&pretty=true&_source_include=citation_title,citation_date,keyword,format,metadatalink,citation_authors

in comparison to:
http://ws.pangaea.de/es/dataportal-oa-icc/pansimple/_search?q=_id:PANGAEA.754785&pretty=true&_source_include=citation_title,citation_date,keyword,format,metadatalink,citation_authors

I haven't found any field "Reference year" in avaible fields exposed by the request:
http://ws.pangaea.de/es/dataportal-oa-icc/pansimple/_search?q=_id:PANGAEA.960176

What do you propose ?
Could you ask to PANGAEA staff to always have have a "citation_date" ?

Do not get your point to use OAICCdb.utf8. For exemple there is no reference to PANGAEA.960176 so no date to extract.

**Comment by PBrockmann** [comment]
Now dates of the publication are consolidated from the 'Supplement To' field.
